<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Alexandra Sears" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/proj2-2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          April 1, 2020
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<pre class="r"><code>jasa&lt;-survival::jasa
jasa&lt;-jasa%&gt;%select(fustat,age,reject,surgery,accept.dt,tx.date,wait.time)%&gt;%
  na.omit%&gt;%mutate(survive=fustat)%&gt;%select(-fustat)
glimpse(jasa)</code></pre>
<pre><code>## Rows: 65
## Columns: 7
## $ age       &lt;dbl&gt; 54.29706, 40.26283, 50.86927, 42.50240, 47.98084, 54.57358,…
## $ reject    &lt;dbl&gt; 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,…
## $ surgery   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ accept.dt &lt;date&gt; 1968-01-06, 1968-03-28, 1968-07-12, 1968-08-11, 1968-08-15…
## $ tx.date   &lt;date&gt; 1968-01-06, 1968-05-02, 1968-08-31, 1968-08-22, 1968-09-09…
## $ wait.time &lt;dbl&gt; 0, 35, 50, 11, 25, 16, 36, 27, 19, 17, 7, 11, 2, 82, 24, 70…
## $ survive   &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,…</code></pre>
<div id="introduction" class="section level4">
<h4>0. Introduction</h4>
<p><em>The data set is the survival of patients on the waiting list for a Stanford heart transplant program in 1974 that was published by John Crowley &amp; Marie Hu[1]. Survive is if the patient survived with 1 being that they died. Age is the age of the patient in years. Reject is whether or not they rejected the transplant with 1 being they did. Surgery is if the had a prior bypass surgery with 1 being they did. accept.dt and tx.dt are the acceptance into the program and the date of the transplant respectively. wait.time is the time before the pateint had the transplant (which is just days between accept.dt and tx.date).There are 65 observations after removing the NAs.</em></p>
</div>
<div id="manova-anova-post-hoc-t-tests" class="section level4">
<h4>1. MANOVA, ANOVA, Post-Hoc t Tests</h4>
<pre class="r"><code>shapiro.test(jasa$age)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  jasa$age
## W = 0.93631, p-value = 0.002338</code></pre>
<pre class="r"><code>shapiro.test(jasa$reject)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  jasa$reject
## W = 0.63232, p-value = 1.738e-11</code></pre>
<pre class="r"><code>shapiro.test(jasa$surgery)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  jasa$surgery
## W = 0.47225, p-value = 6.437e-14</code></pre>
<pre class="r"><code>shapiro.test(jasa$wait.time)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  jasa$wait.time
## W = 0.63669, p-value = 2.071e-11</code></pre>
<pre class="r"><code>jasa%&gt;% select(age,reject,surgery,wait.time)%&gt;%cor</code></pre>
<pre><code>##                   age     reject     surgery   wait.time
## age        1.00000000  0.4289776 -0.02497560  0.01183281
## reject     0.42897762  1.0000000 -0.18776413 -0.19880603
## surgery   -0.02497560 -0.1877641  1.00000000  0.05814853
## wait.time  0.01183281 -0.1988060  0.05814853  1.00000000</code></pre>
<pre class="r"><code>df&lt;-rmvnorm(1000,mean=c(0,0),sigma=matrix(c(1,.5,.5,1),ncol=2,byrow=T))
df&lt;-data.frame(jasa)%&gt;%rename(Y1=survive,Y2=age)
p&lt;-ggplot(df, aes(Y1,Y2))+theme_classic()+xlim(-10, 10)+geom_point(alpha=.5)+geom_density_2d(h=2)+coord_fixed()
ggMarginal(p,type=&quot;density&quot;,xparams = list(bw=.5), yparams=list(bw=.5))</code></pre>
<p><img src="/proj2-2_files/figure-html/unnamed-chunk-2-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(jasa, aes(x = age, y = wait.time)) +
  geom_point(alpha = .5) + geom_density_2d(h=2) + coord_fixed() + facet_wrap(~survive)+
  scale_x_continuous(breaks = seq(20, 62, by = 20))+theme_classic(base_size = 10)</code></pre>
<p><img src="/proj2-2_files/figure-html/unnamed-chunk-2-2.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>covmats&lt;-jasa%&gt;%select(survive,age,reject,surgery,wait.time)%&gt;%group_by(survive)%&gt;%do(covs=cov(.[2:5]))
for(i in 1:3){print(as.character(covmats$survive[i])); print(covmats$covs[i])}</code></pre>
<pre><code>## [1] &quot;0&quot;
## [[1]]
##                  age reject    surgery  wait.time
## age       83.8716976      0  0.6213681   86.27593
## reject     0.0000000      0  0.0000000    0.00000
## surgery    0.6213681      0  0.2155797   -2.23913
## wait.time 86.2759277      0 -2.2391304 4777.73913
## 
## [1] &quot;1&quot;
## [[1]]
##                   age      reject     surgery   wait.time
## age       65.51982685  1.24270713 -0.04675882   20.075196
## reject     1.24270713  0.21219512 -0.01341463   -1.977439
## surgery   -0.04675882 -0.01341463  0.10975610    1.667683
## wait.time 20.07519574 -1.97743902  1.66768293 1181.230488
## 
## [1] NA
## [[1]]
## NULL</code></pre>
<pre class="r"><code>man1&lt;-manova(cbind(age,reject,surgery,wait.time)~survive, data=jasa)
summary(man1)</code></pre>
<pre><code>##           Df  Pillai approx F num Df den Df    Pr(&gt;F)    
## survive    1 0.49649   14.791      4     60 1.826e-08 ***
## Residuals 63                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>##  Response age :
##             Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## survive      1  752.1  752.14  10.415 0.001985 **
## Residuals   63 4549.8   72.22                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response reject :
##             Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## survive      1 7.5737  7.5737  56.215 2.7e-10 ***
## Residuals   63 8.4878  0.1347                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response surgery :
##             Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## survive      1 0.4360 0.43604  2.9385 0.09141 .
## Residuals   63 9.3486 0.14839                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response wait.time :
##             Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## survive      1   7898  7898.2  3.1666 0.07998 .
## Residuals   63 157137  2494.2                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>jasa%&gt;%group_by(survive)%&gt;%summarize(mean(age),mean(reject))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   survive `mean(age)` `mean(reject)`
##     &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;
## 1       0        41.6          0    
## 2       1        48.6          0.707</code></pre>
<pre class="r"><code>pairwise.t.test(jasa$age, jasa$survive, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  jasa$age and jasa$survive 
## 
##   0    
## 1 0.002
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(jasa$reject, jasa$survive, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  jasa$reject and jasa$survive 
## 
##   0      
## 1 2.7e-10
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>1-.95^(7) #error rate</code></pre>
<pre><code>## [1] 0.3016627</code></pre>
<pre class="r"><code>0.05/(7) #bonferroni corrections</code></pre>
<pre><code>## [1] 0.007142857</code></pre>
<p><em>After performing the MANOVA to determine differences in survival with my dependent variables, the p value is less than 0.05, with an F value of 14.791 which means there are mean differences across the levels of survive (dead,1 or alive,0). When I performed univariate ANOVAs, I found that the mean differences that were significant occur across age and reject. I performed 1 MANOVA, 4 ANOVA, and 2 post hoc t tests. The probability of type I error unadjusted is 30.16627%. Adjusted according to Bonferroni correction it is 0.007142857. Age and reject are still significant after the correction. The significant differences in survival were age of the patient and if they rejected the transplant. Assumptions that were probably met were sample size because there are 65 observations, no extreme outliers, and no multicollinearity. Assumptions that were not met are multivariate normality and homogeneity of (co)variances because they are not similar across the groups and multivariate normality of DVs.</em></p>
</div>
<div id="randomization-test" class="section level4">
<h4>2. Randomization Test</h4>
<pre class="r"><code>jasar&lt;-jasa%&gt;%select(survive,age)
jasar%&gt;%group_by(survive)%&gt;%summarize(means=mean(age))%&gt;%summarize(`mean_diff:`=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `mean_diff:`
##          &lt;dbl&gt;
## 1         7.05</code></pre>
<pre class="r"><code>rand_dist&lt;-vector()
for(i in 1:5000){
new&lt;-data.frame(age=sample(jasar$age),survive=jasa$survive)
rand_dist[i]&lt;-mean(new[new$survive==1,]$age)-
mean(new[new$survive==0,]$age)}
hist(rand_dist,main=&quot;Survival by Age&quot;,ylab=&quot;Age&quot;);abline(v = 7.0487 ,col=&quot;blue&quot;); abline(v = -7.0487    ,col=&quot;blue&quot;)</code></pre>
<p><img src="/proj2-2_files/figure-html/unnamed-chunk-3-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(rand_dist&gt;7.0487    | rand_dist&lt; -7.0487   )</code></pre>
<pre><code>## [1] 0.002</code></pre>
<pre class="r"><code>ggplot(jasar,aes(age,fill=survive))+geom_histogram(bins=6.5)+facet_wrap(~survive,ncol=2)+theme(legend.position=&quot;none&quot;+theme_classic())</code></pre>
<p><img src="/proj2-2_files/figure-html/unnamed-chunk-3-2.png" width="672" style="display: block; margin: auto;" /></p>
<p><em>I used a randomization test in which the null hypothesis was that mean age is the same for people that survived vs people that did not survive surgery. The alternate hypothesis is that the mean age is different for people that survived vs people that did not survive. The two-tailed p value is 0.0012 so we can reject the null hypothesis. This means the mean age is different for people that survived vs people that did not survive.</em></p>
</div>
<div id="linear-regression-model" class="section level4">
<h4>3. Linear Regression Model</h4>
<pre class="r"><code>jasa$wait.t_c&lt;-jasa$wait.time-mean(jasa$wait.time)
fit&lt;-lm(age~(reject+surgery+wait.t_c)^2,data=jasa,family=&quot;binomial&quot;)
summary(fit) </code></pre>
<pre><code>## 
## Call:
## lm(formula = age ~ (reject + surgery + wait.t_c)^2, data = jasa, 
##     family = &quot;binomial&quot;)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -22.3021  -4.9398   0.2949   5.5796  15.4779 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      41.61966    1.63295  25.487  &lt; 2e-16 ***
## reject            9.15935    2.37888   3.850 0.000297 ***
## surgery           2.52725    3.50732   0.721 0.474073    
## wait.t_c          0.01303    0.02448   0.532 0.596498    
## reject:surgery   -5.16905    7.14623  -0.723 0.472387    
## reject:wait.t_c  -0.01077    0.06020  -0.179 0.858633    
## surgery:wait.t_c  0.04142    0.07543   0.549 0.585043    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.452 on 58 degrees of freedom
## Multiple R-squared:  0.2186, Adjusted R-squared:  0.1378 
## F-statistic: 2.704 on 6 and 58 DF,  p-value: 0.02201</code></pre>
<pre class="r"><code>ggplot(jasa, aes(x=wait.t_c, y=age,group=reject))+theme_classic()+geom_point(aes(color=reject))+
  geom_smooth(method=&quot;lm&quot;,formula=y~1,se=F,fullrange=T,aes(color=reject))+
theme(legend.position=c(.9,.25))+xlab(&quot;Wait.t_c&quot;)+ggtitle(&quot;Linear Regression of Age with Wait Time and Rejection Status&quot;)</code></pre>
<p><img src="/proj2-2_files/figure-html/unnamed-chunk-4-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#linear relationships
resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids), color=&quot;blue&quot;)+theme_classic()</code></pre>
<p><img src="/proj2-2_files/figure-html/unnamed-chunk-4-2.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#normality 
shapiro.test(resids)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.98402, p-value = 0.5657</code></pre>
<pre class="r"><code>#equal variance
bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 16.459, df = 6, p-value = 0.01149</code></pre>
<pre class="r"><code>coeftest(fit, vcov = vcovHC(fit))[,1:2] </code></pre>
<pre><code>##                     Estimate Std. Error
## (Intercept)      41.61966319 2.17949239
## reject            9.15935082 2.41279475
## surgery           2.52724593 3.32884133
## wait.t_c          0.01303268 0.01711262
## reject:surgery   -5.16904959 5.15002485
## reject:wait.t_c  -0.01076983 0.02790342
## surgery:wait.t_c  0.04141895 0.07740921</code></pre>
<p><em>When reject and surgery are 0 and wait time is the average, age is 41.620 years old. When reject is 1, the age goes up by 9.160 years, when surgery is 1, the age goes up by 2.527 years, and when wait time is the average, age goes up by 0.013 years. When you compare reject to surgery, age goes down by 5.170 years. When you compare reject to average wait time, age goes down by 0.011 years. When you compare surgery to average wait time, age goes up by 0.041 years. Linearity looked to be supported. Normality was supported. Equal variance was rejected with the BP test so I corrected with robust SEs. The SEs increased for the intercept, reject, wait.t_c, and surgery:wait.t_c. They decreased for surgery, reject:surgery, and reject:wait.t_c. My model explains 21.86% of the variation in the outcome.</em></p>
</div>
<div id="linear-regression-model-with-bootstrapped-ses" class="section level4">
<h4>4. Linear Regression Model with Bootstrapped SEs</h4>
<pre class="r"><code>samp_distn&lt;-replicate(5000, {
  boot_dat&lt;-jasa[sample(nrow(jasa),replace=TRUE),]
  fit&lt;-lm(age~(reject+surgery+wait.t_c)^2, data=boot_dat) 
  coef(fit)})

samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept)  reject surgery   wait.t_c reject:surgery reject:wait.t_c
## 1     2.18559 2.42071 5.31389 0.04416992             NA      0.05319001
##   surgery:wait.t_c
## 1               NA</code></pre>
<p><em>The SEs in this bootstrapped model increased from all the robust SEs. And different from the original SEs by increasing for the intercept, reject, wait.t_c, and reject:wait.t_c, and decreased for surgery.</em></p>
</div>
<div id="logistic-regression-and-10-fold-cv" class="section level4">
<h4>5. Logistic Regression and 10-Fold CV</h4>
<pre class="r"><code>jasa$age_c&lt;-jasa$age-mean(jasa$age)
jasa1&lt;-jasa %&gt;%mutate(survive=replace(survive, survive==1, &quot;dead&quot;),survive=replace(survive, survive==0, &quot;alive&quot;)) %&gt;% as.data.frame()

data&lt;-jasa1%&gt;%mutate(y=ifelse(survive==&quot;dead&quot;,1,0))
outcome&lt;-factor(data$survive,levels=c(&quot;dead&quot;,&quot;alive&quot;))

fit1&lt;-glm(y~age_c+reject+surgery+wait.t_c, data=data,family=&quot;binomial&quot;)
coeftest(fit1)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##                Estimate  Std. Error z value Pr(&gt;|z|)
## (Intercept) -3.6834e-01  4.2842e-01 -0.8598   0.3899
## age_c        3.9205e-02  3.8496e-02  1.0184   0.3085
## reject       1.9826e+01  1.9698e+03  0.0101   0.9920
## surgery     -7.7083e-01  9.1745e-01 -0.8402   0.4008
## wait.t_c    -5.2316e-03  7.1092e-03 -0.7359   0.4618</code></pre>
<pre class="r"><code>exp(coef(fit1))</code></pre>
<pre><code>##  (Intercept)        age_c       reject      surgery     wait.t_c 
## 6.918853e-01 1.039984e+00 4.075661e+08 4.626275e-01 9.947821e-01</code></pre>
<pre class="r"><code>probs&lt;-predict(fit1,type=&quot;response&quot;)
table(predict=as.numeric(probs&gt;.5),truth=data$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict  0  1 Sum
##     0   22 10  32
##     1    2 31  33
##     Sum 24 41  65</code></pre>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  prediction&lt;-ifelse(probs&gt;.5,1,0)
  acc=mean(truth==prediction)
  sens=mean(prediction[truth==1]==1)
  spec=mean(prediction[truth==0]==0)
  ppv=mean(truth[prediction==1]==1)
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
data.frame(acc,sens,spec,ppv,auc)}
class_diag(probs,data$y)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.8153846 0.7560976 0.9166667 0.9393939 0.8973577</code></pre>
<pre class="r"><code>data$logit&lt;-predict(fit1,type=&quot;link&quot;)
data%&gt;%ggplot()+geom_density(aes(logit,color=outcome,fill=outcome), alpha=.4)+
  theme_classic()+geom_vline(xintercept=0)+xlab(&quot;logit (log-odds)&quot;)+
  geom_rug(aes(logit,color=outcome))+
  geom_text(x=-5,y=.07,label=&quot;TN = 31&quot;)+
  geom_text(x=-1.75,y=.008,label=&quot;FN = 10&quot;)+
  geom_text(x=1,y=.006,label=&quot;FP = 2&quot;)+
  geom_text(x=5,y=.04,label=&quot;TP = 22&quot;)</code></pre>
<p><img src="/proj2-2_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ROCplot&lt;-ggplot(data)+geom_roc(aes(d=y,m=probs), n.cuts=0)+theme_classic()
ROCplot</code></pre>
<p><img src="/proj2-2_files/figure-html/unnamed-chunk-6-2.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.8973577</code></pre>
<pre class="r"><code>set.seed(1234)
k=10
data1&lt;-data[sample(nrow(data)),] 
folds&lt;-cut(seq(1:nrow(data)),breaks=k,labels=F) 
diags&lt;-NULL
for(i in 1:k){         
  train&lt;-data[folds!=i,] 
  test&lt;-data[folds==i,]  
  truth&lt;-test$y
  fit&lt;-glm(y~age_c+reject+surgery+wait.t_c,data=train,family=&quot;binomial&quot;)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(probs,truth)) }
summarize_all(diags,mean) </code></pre>
<pre><code>##         acc      sens spec       ppv       auc
## 1 0.7642857 0.7571429  NaN 0.9016667 0.8583333</code></pre>
<p><em>When a person is at the average age, the odds that they died is 1.03. When reject is 0 the odds that they died are 407566106. When surgery is 0 the odds that they died is -0.77. When a person has an average wait time the odds that they died is -0.005. There were 22 true positives, 31 true negatives, 2 false positives, and 10 false negatives. The AUC is 0.897 so it is a great tradeoff between sensitivity and specificity for my data. When you use a 10-fold CV it goes down to 0.858, so there is evidence of overfitting. The average out-of-sample accuracy is 0.814, the sensitivity is 0.755, and the recall is 0.925.</em></p>
</div>
<div id="lasso-and-10-fold-cv" class="section level4">
<h4>6. LASSO and 10-Fold CV</h4>
<pre class="r"><code>set.seed(1234)
y&lt;-as.matrix(data$y) #grab response
x&lt;-model.matrix(y~age_c+reject+surgery+wait.t_c,data=data)[,-1]
cv &lt;- cv.glmnet(x,y)
cv&lt;-cv.glmnet(x,y,family=&quot;binomial&quot;)
lasso&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 5 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                    s0
## (Intercept) -0.151940
## age_c        .       
## reject       1.811409
## surgery      .       
## wait.t_c     .</code></pre>
<pre class="r"><code>set.seed(1234)
k=10
data &lt;- data%&gt;% sample_frac #put rows of dataset in random order
folds &lt;- ntile(1:nrow(data),n=10) #create fold labels
diags&lt;-NULL
for(i in 1:k){
train &lt;- data[folds!=i,] #create training set (all but fold i)
test &lt;- data[folds==i,] #create test set (just fold i)
truth &lt;- test$y #save truth labels from fold i
fit &lt;- glm(y~reject,
data=train, family=&quot;binomial&quot;)
probs &lt;- predict(fit, newdata=test, type=&quot;response&quot;)
diags&lt;-rbind(diags,class_diag(probs,truth))
}
diags%&gt;%summarize_all(mean)</code></pre>
<pre><code>##         acc sens spec ppv   auc
## 1 0.8142857 0.69    1   1 0.845</code></pre>
<p><em>When I used a LASSO, the only variable maintained is reject which makes sense. If someone rejects their transplant they are more likely to die. When I ran a 10-fold CV with just reject the accuracy went up from 0.762 to 0.0814.</em></p>
<p>###Sources</p>
<p><em>[1] John Crowley &amp; Marie Hu (1977) Covariance Analysis of Heart Transplant
Survival Data, Journal of the American Statistical Association, 72:357, 27-36</em>
…</p>
</div>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
